services:
  # Frontend Service (React + Vite)
  frontend:
    build:
      context: ./hikemap-frontend
      dockerfile: Dockerfile
    image: hikemap-frontend
    container_name: hikemap-frontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - hikemap-network

  # Backend Service (Spring Boot)
  backend:
    build:
      context: ./hikemap-backend
      dockerfile: Dockerfile
    image: hikemap-backend
    container_name: hikemap-backend
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - hikemap-network

  # Database Service (PostgreSQL with PostGIS)
  postgres:
    image: postgis/postgis:17-3.5
    container_name: hikemap-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hikemap-network

  # Database Migrations (Liquibase)
  liquibase:
    image: liquibase/liquibase:4.29
    container_name: hikemap-liquibase
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./hikemap-backend/migrations:/migrations:z
    command:
      - --searchPath=/migrations
      - --changelog-file=/master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    networks:
      - hikemap-network

volumes:
  postgres-data:

networks:
  hikemap-network:
    driver: bridge
